# Actividad 4.1

In [4]:
import pandas as pd
import numpy as np

# Crear un dataframe valores nulos
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', None],
    'Edad': [23, np.nan, 35, 29],
    'Ciudad': ['CDMX', 'Guadalajara', None, 'Monterrey']
}


df = pd.DataFrame(data)
display(df)
display(df.isnull())
display(df.notnull())

print(df.isnull().sum())

df.info()

   Nombre  Edad       Ciudad
0     Ana  23.0         CDMX
1    Luis   NaN  Guadalajara
2  Carlos  35.0          NaN
3     NaN  29.0    Monterrey

   Nombre   Edad  Ciudad
0   False  False   False
1   False   True   False
2   False  False    True
3    True  False   False

   Nombre   Edad  Ciudad
0    True   True    True
1    True  False    True
2    True   True   False
3   False   True    True

Nombre    1
Edad      1
Ciudad    1
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  3 non-null      str
 1   Edad    3 non-null      float64
 2   Ciudad  3 non-null      str
dtypes: float64(1), str(2)
memory usage: 228.0 bytes